name: If statements
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_REF:11}"
      # - run: echo "${github.action_ref}"

      - run: echo "PreRelease"
        # if github release tag contains - then its a prerelease
        if: ${{ contains(github.action_ref, '-') }}

      - run: echo "Normal Release"
        # if github release tag doesn't contains - then its a normal release
        if: ${{ !contains(github.action_ref, '-') }}
